// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Teste.Capitani.Infra.Repositories.MainContext;

namespace Teste.Capitani.Infra.Repositories.MainContext.Migrations
{
    [DbContext(typeof(MainUnitOfWork))]
    [Migration("20200711041801_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Teste.Capitani.Domain.MainContext.Aggs.CidadeAgg.Cidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EstadoId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EstadoId");

                    b.ToTable("Cidades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EstadoId = 1,
                            Nome = "São Paulo"
                        },
                        new
                        {
                            Id = 2,
                            EstadoId = 1,
                            Nome = "Barueri"
                        },
                        new
                        {
                            Id = 3,
                            EstadoId = 1,
                            Nome = "Osasco"
                        },
                        new
                        {
                            Id = 4,
                            EstadoId = 2,
                            Nome = "Rio de Janeiro"
                        },
                        new
                        {
                            Id = 5,
                            EstadoId = 2,
                            Nome = "Cabo Frio"
                        },
                        new
                        {
                            Id = 6,
                            EstadoId = 2,
                            Nome = "Arraial do Cabo"
                        },
                        new
                        {
                            Id = 7,
                            EstadoId = 3,
                            Nome = "Cuiaba"
                        },
                        new
                        {
                            Id = 8,
                            EstadoId = 3,
                            Nome = "Chamada dos Guimaraes"
                        },
                        new
                        {
                            Id = 9,
                            EstadoId = 3,
                            Nome = "Santo Antonio"
                        });
                });

            modelBuilder.Entity("Teste.Capitani.Domain.MainContext.Aggs.EstadoAgg.Estado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Estados");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Sao Paulo"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Rio de Janeiro"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Mato Grosso"
                        });
                });

            modelBuilder.Entity("Teste.Capitani.Domain.MainContext.Aggs.PessoaAgg.Pessoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cep")
                        .HasColumnType("nvarchar(8)")
                        .HasMaxLength(8);

                    b.Property<int>("CidadeId")
                        .HasColumnType("int");

                    b.Property<string>("Cpf")
                        .HasColumnType("nvarchar(11)")
                        .HasMaxLength(11);

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("CidadeId");

                    b.ToTable("Pessoas");
                });

            modelBuilder.Entity("Teste.Capitani.Domain.MainContext.Aggs.CidadeAgg.Cidade", b =>
                {
                    b.HasOne("Teste.Capitani.Domain.MainContext.Aggs.EstadoAgg.Estado", "Estado")
                        .WithMany("Cidades")
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Teste.Capitani.Domain.MainContext.Aggs.PessoaAgg.Pessoa", b =>
                {
                    b.HasOne("Teste.Capitani.Domain.MainContext.Aggs.CidadeAgg.Cidade", "Cidade")
                        .WithMany()
                        .HasForeignKey("CidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
